server:
  port: ${port:8080}

zk:
  servers: 192.168.222.20:2181,192.168.222.30:2181,192.168.222.40:2181
  namespace: elastic-job-demo

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root